# Generated by Django 4.1.7 on 2023-02-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='registration date')),
            ],
        ),
    ]
