# Generated by Django 4.1.7 on 2023-02-21 15:40

from django.db import migrations


def create_data(apps, schema_editor):
    student = apps.get_model('students', 'Student')
    student(
        name="Steve Bell",
        email="stbell@gmail.com",
        document="156151",
        phone="51513112"
    ).save()


class Migration(migrations.Migration):
    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
